Fix error when HostConfig is not defined in API request
piontec/docker-enforcer pull request #47
Opened 2017-10-13 20:41 UTC by georgyturevich

Fix error when HostConfig is not defined in API request (e.g `sudo curl -H "Content-Type: application/json" -X POST -d '{"Image":"ubuntu"}' http://localhost:2375/containers/create` )

2018-01-05 11:19 UTC, piontec requested changes
please rebase against current `develop`

2018-01-05 11:19 UTC, piontec commented on docker_enforcer.py
> +    cont_json["HostConfig"] = {} if "HostConfig" not in cont_json else cont_json["HostConfig"]
does it really make sense to add empty `HostConfig` here? maybe we should just refuse and return error? I think that docker CLI always puts some reasonable defaults there, even if default parameters are used. Other API clients should do as well, right? I don't remember now from where do we have this example of non-existing `HostConfig`...?

2018-01-10 19:55 UTC, georgyturevich commented
@piontec Lukasz, I have rebased the PR just now. Could you merge it?

2018-01-12 14:30 UTC, merged

2018-01-12 14:31 UTC, georgyturevich commented on docker_enforcer.py
> +    cont_json["hostconfig"] = cont_json.get("hostconfig", {})
@piontec Hi Lukasz,

I rebased the branch again. During rebasing I found one possible bug. We had `cont_json.get("labels", [])` before lowering letters. So most likely cont_json would contain `Labels`. So I moved `docker_helper.rename_keys_to_lower(cont_json)` two lines upper.

I also simplified cont_json["hostconfig"] initialization. I replaced `{} if "hostconfig" not in cont_json else cont_json["hostconfig"]` with `cont_json.get("hostconfig", {})`